# Generated by Django 5.0.3 on 2024-03-28 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, default='', max_length=50)),
                ('barcode', models.CharField(blank=True, default='', max_length=20)),
                ('product_weight', models.IntegerField()),
                ('caloric', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcal.breakfast')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcal.dinner')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calcal.lunch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_menu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lunch',
            name='product',
            field=models.ManyToManyField(to='calcal.product'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='product',
            field=models.ManyToManyField(to='calcal.product'),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='product',
            field=models.ManyToManyField(to='calcal.product'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=6)),
                ('tall', models.IntegerField()),
                ('year_birth', models.CharField(max_length=4)),
                ('activity_lvl', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('goal_weight', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('caloric', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
