# Generated by Django 5.0.3 on 2024-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0002_breakfast_dinner_lunch_product_menu_lunch_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='product',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='caloric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='product_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='caloric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='product_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='caloric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='product_weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='product',
            field=models.CharField(default='any_name', max_length=200),
        ),
        migrations.AddField(
            model_name='lunch',
            name='product',
            field=models.CharField(default='any_name', max_length=200),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='dinner',
            name='product',
            field=models.CharField(default='any_name', max_length=200),
        ),
    ]
