# Generated by Django 5.0.3 on 2024-03-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0003_remove_breakfast_product_remove_lunch_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='day',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dinner',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='lunch',
        ),
        migrations.AddField(
            model_name='menu',
            name='breakfast',
            field=models.ManyToManyField(to='calcal.breakfast'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dinner',
            field=models.ManyToManyField(to='calcal.dinner'),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch',
            field=models.ManyToManyField(to='calcal.lunch'),
        ),
    ]
