# Generated by Django 5.0.3 on 2024-03-31 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0004_remove_menu_day_breakfast_day_dinner_day_lunch_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dinner',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lunch',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_l', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
