# Generated by Django 5.0.3 on 2024-03-31 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0005_breakfast_user_dinner_user_lunch_user_delete_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='user',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='user',
            field=models.ManyToManyField(default='', related_name='user_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dinner',
            name='user',
            field=models.ManyToManyField(default='', related_name='user_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lunch',
            name='user',
            field=models.ManyToManyField(default='', related_name='user_l', to=settings.AUTH_USER_MODEL),
        ),
    ]
