# Generated by Django 5.0.3 on 2024-03-31 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0006_remove_breakfast_user_remove_dinner_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='user',
            field=models.ManyToManyField(related_name='user_d', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='user',
            field=models.ManyToManyField(related_name='user_l', to=settings.AUTH_USER_MODEL),
        ),
    ]
