# Generated by Django 5.0.3 on 2024-03-31 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcal', '0008_alter_breakfast_user_alter_dinner_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='user',
        ),
        migrations.AddField(
            model_name='breakfast',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dinner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lunch',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
